name: Posting Bot

"on":
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    uses: ./.github/workflows/dashboard.yml
    with:
      mode: post
      max_profiles: ""
      dry_run: false
      populate_img_links: false
      populate_limit: ""
      populate_write: false
      headless: true
      debug: false
    secrets: inherit
